[project]
name = "vdh-audio-keeper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyinstaller>=6.22.3",
    "wxpython>=4.3.1",
]

[project.scripts]
vdh-audio-keeper = "vdh_audio_keeper:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
